apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frontend
spec:
  serviceName: frontend
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        component: opentracing-example
        version: v0.0.1
    spec:
      containers:
      - name: frontend
        image: pgillich/opentracing-example:v0.0.1-4-gd99fd63
        imagePullPolicy: "IfNotPresent"
        command: ["/usr/local/bin/opentracing-example"]
        args: ["frontend"]
        ports:
          - containerPort: 80
        env:
        - name: LISTENADDR
          value: ":80"
        - name: INSTANCE
          value: "-"
        - name: JAEGERURL
          value: "-"
        - name: OTLPURL
          value: "http://tempo.istio-system.svc:4318"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
   - port: 80
  selector:
   app: frontend
